# Generated by Django 6.0.3 on 2026-03-16 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hostel_app", "0004_complaint_priority"),
    ]

    operations = [
        migrations.AddField(
            model_name="complaint",
            name="category",
            field=models.CharField(default="General", max_length=20),
        ),
    ]
