# Generated by Django 6.0.3 on 2026-03-12 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hostel_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fee",
            name="status",
            field=models.CharField(default="Pending", max_length=10),
        ),
    ]
