# Generated by Django 6.0.3 on 2026-03-15 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hostel_app", "0003_visitor"),
    ]

    operations = [
        migrations.AddField(
            model_name="complaint",
            name="priority",
            field=models.CharField(default="Medium", max_length=20),
        ),
    ]
