# Generated by Django 6.0.3 on 2026-04-06 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hostel_app", "0005_complaint_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
