# Generated by Django 6.0.3 on 2026-04-07 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hostel_app", "0007_notice_fee_due_date_student_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="room_number",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
